### PR TITLE
feat: add date binning functionality

### PR DESCRIPTION
**Pull request by HKuz**
Start of the binning functionality (#8 ).

All class code and tests are in the Jupyter notebook (UPDATE: code is in `Period` class, tests moved to `tests` folder, and the Jupyter notebook is deleted). Other items:

- [x] Reconfigure `__init__` to work as an XStateDocument => updated requirement: reconfigure as framework-neutral class
- [x] Add error handling for bad/missing inputs
- [x] Add function to convert bins to a different periodicity
- [x] Add functionality to 'redistribute' data from one binning structure to another (i.e. sales given in Calendar months converted to sales binned by ISO Weeks). Assumes data is uniformly distributed over given periods in order to redistribute it into new bins
- [x] Add ability to specify a different weekday as week starting date ("ISO Week" is default)
- [x] Update `get_cal_start_dates` so to include a step for "days" with a custom number of days as the delta (accommodates e.g. 14-day pay periods)
- [x] Update period labels for all scenarios, include ability to pass a custom format string, add tests
- [x] Convert tests to Pytest
- Documentation is currently in detailed docstrings

For reference, the steps to run the notebook in a local bench are below:

```shell
# Activate the environment:
source env/bin/activate

# Install Jupyter (it's not automatically part of the env):
pip install jupyter

# Launch Jupyter (this will open a browser window - navigate to apps/forecast and open the notebook):
jupyter notebook

# When done: save, close and halt the notebook, close windows. Kill process in command line via ctrl-c twice

# Deactivate the environment:
source deactivate
```

### CODE REVIEW

**Comment by HKuz** [comment]
Update: latest push includes working code for the financial redistribution. As promised, this first cut is a bit 'brute force' - it basically figures out the financials on a per day basis (given the period info of original data) then sums that based on the new bins. Plenty of room for refinement...

**Comment by agritheory** [comment]
@HKuz This looks great so far. I am going to add some separate tickets for testing

**Comment by HKuz** [comment]
@agritheory sounds good - I just refactored things a tad and have the contextvars working in latest push. I'm tackling the pytest conversion now.

**Comment by HKuz** [comment]
@agritheory I re-worked this a bit to accommodate the "biweekly" ask and finish up some remaining items that were on the original list. Should be in good shape and could be useful for the `fab` work.

- the `Period` class supports a list of different periodicities. There are a number of ISO-based ones, then a number of calendar-based ones. For simple biweekly date bins that return 14-day periods from the given start date (whatever weekday that happens to be), you'd use a `periodicity` of "Biweekly". I also added a "Custom Days" option where the user can pass a number of days for ultimate flexibility
- finished the labels section. I took a stab for some period labels that we can change as needed, also has functionality to pass a custom format string to apply the the bin dates
- some refactoring of assumptions - the `end_date` is now inclusive by default and I simplified the bin calcs for "Calendar Month" and "Calendar Quarter" - it creates the bins based on whichever day of the month is given via `start_date`

**Pull request merged**
